name: Node.js CI

on:
  push:
    branches:
      - master  # Cambié "main" por "master"
  pull_request:
    branches:
      - master  # Cambié "main" por "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Puedes usar la versión que prefieras

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --coverage --coverageReporters=html  # Genera reporte de cobertura en HTML

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/  # Sube el directorio donde Jest genera el reporte HTML
